on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - id: backend-deployment
      uses: Zimboboys/express-deployment-aws@v0.1.0
      with:
        s3-bucket: 'meals-that-connect-deployment'
        stack-name: 'meals-that-connect-deployment-stack'
      env:
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        ADMIN_CODE: ${{ secrets.ADMIN_CODE }}

    - run: echo API is at ${{ steps.backend-deployment.outputs.api-url }}
      shell: bash
